const quotes = [
  "How are you today, truly?\nYou’ve been moving through your day with strength, even if it doesn’t always feel like it. Before you scroll again or rush into the next thing, try this: take three deep breaths. Let your shoulders soften. Let your mind settle. And hey, if you haven’t eaten yet—don’t skip your breakfast. A nourishing morning meal stabilizes your energy, fuels your brain, and reminds your body it’s loved. You deserve the kind of care you often give to others.",
  "I know it’s a tiring day, and you’ve been giving it your all.\nSometimes the weight of tasks and to-dos hides how amazing it is that you showed up at all. Pause for a moment and drink a glass of water slowly. Even simple hydration can uplift your mood, reduce fatigue, and refresh your mind. Your body is doing so much for you every second—this small kindness counts. You deserve ease, and today, it starts with one sip.",
  "You’ve been carrying so much, quietly and bravely.\nEven your silence is strong. But strength isn’t always about holding on—it’s also about letting go. If your eyes feel strained or your head aches from too much screen time, remember the 20-20-20 rule: every 20 minutes, look at something 20 feet away for 20 seconds. It helps your eyes reset, and your mind too. You deserve comfort, even in the smallest details of your day.",
  "You’ve done more than enough already.\nIt’s okay to pause without guilt. You are allowed to stop, breathe, and rest—just because you exist. Take 5 minutes for a gentle stretch. Feel your body awaken from stillness. Movement improves circulation and clears mental fog. You’re not just surviving—you’re growing. You deserve time to slow down and bloom, quietly and fully.",
  "You show up for others with so much love.\nBut today, please show up for yourself too. One simple way? Prepare a colorful meal. Add some greens, a splash of fruit, maybe a warm bowl of something soothing. Your body thrives on variety—fiber for gut health, color for nutrients, warmth for comfort. You are not an afterthought. You deserve to be nourished like someone deeply loved.",
  "Hey, sweet soul, you’re doing so much.\nTake a moment to notice how far you’ve come, even on the hard days. If your shoulders are tight or your mind feels heavy, try rolling your neck gently or stretching your arms. Small movements release big tensions. And don’t forget to sip water—it keeps your energy steady and your mind clear. You deserve care that feels like a warm hug.",
  "You’re allowed to feel what you feel today.\nNo need to push it down or rush through it. Emotions are visitors, not enemies. Try journaling for just five minutes—let the words spill without judgment. It can lighten your heart. And if you’re low on energy, a piece of fruit can be a quick, natural boost. You deserve space to process and heal.",
  "You light up the world in your own quiet way.\nBut don’t forget to shine that light on yourself too. Step outside for a moment, even just to feel the air. A short walk or a breath of fresh air lowers stress and lifts your mood. Your body loves the outdoors as much as your soul does. You deserve moments that feel alive.",
  "You don’t have to be perfect to be enough.\nYou are already worthy, just as you are. If your day feels scattered, try this: make a small list of three things you can do for yourself. One could be as simple as eating a warm, nourishing meal. Food is fuel, but it’s also love. You deserve care that anchors you.",
  "You’re navigating so much with grace.\nEven when you stumble, you’re still moving forward. Pause and check in with your body—are you holding tension in your jaw or shoulders? Release it with a slow exhale and a gentle stretch. And don’t skip your lunch today; a balanced meal keeps your blood sugar steady and your focus sharp. You deserve strength for the journey.",
  "You’ve been holding so much, quietly and bravely.\nEven when you feel invisible, your strength speaks loudly. But no one is meant to carry it all alone. Close your eyes and try box breathing: inhale for 4 counts, hold for 4, exhale for 4, and hold for 4 again. Just a minute can bring calm to an anxious heart. And if you’ve been running on empty, grab a wholesome snack—your body deserves steady energy, not survival mode. You deserve care that starts within.",
  "You’re doing your best, even when no one sees it.\nProgress isn’t always visible. Just getting out of bed can be a victory. Try saying one kind thing to yourself today. Even “I’m trying” or “I’m worthy” can rewire how you think. Self-talk shapes how we heal. And don’t forget—a small dose of sunlight helps boost serotonin. Step outside, even briefly. Let the light meet your skin. You deserve to feel whole, not hurried.",
  "I know your mind is juggling so many tabs right now.\nGive it a little room to breathe. Set a timer and take a 15-minute break from all screens. No scrolling. Just being. Unplugging reduces stress, improves sleep, and helps your nervous system reset. You are not just a machine responding to alerts. You are a soul, and you deserve quiet spaces too.",
  "You’ve been pouring energy into everyone around you.\nPlease, refill your own cup too. Put on a song you love. Let your body sway or stretch. Movement—no matter how small—releases tension and boosts mood. Just five minutes can awaken joy where exhaustion lives. And if your head’s pounding, ask yourself—have I had enough water today? You deserve energy that doesn’t come from overdrive.",
  "You, the quiet warrior.\nSometimes the kindest thing you can do is cancel a plan, reschedule a task, or say no. Honor your limits—they are not weaknesses, they are wisdom. Try writing down just three priorities today instead of ten. It helps reduce overwhelm and increases focus. And while you’re at it, eat something warm—it soothes the gut and comforts the heart. You deserve a life paced with peace.",
  "How are you feeling beneath all the rushing?\nNot what you’re doing—but how are you, really? Before you give the world more of yourself, pause to check in. A warm cup of tea, a slow exhale, a look out the window—sometimes that’s enough to reconnect. And please, don’t skip meals today. Your brain needs fuel, your heart needs gentleness. You deserve nourishment, not just accomplishment.",
  "You work so hard—mentally, physically, emotionally.\nEven when it doesn’t get noticed, I see it. Let today be a day where you speak to yourself with the kindness you give your dearest friend. If you’ve been sitting for hours, stand and stretch your arms overhead. Move your spine. Breathe into your ribcage. Movement brings clarity, and clarity brings ease. You deserve to feel free in your own body.",
  "I know you’ve been trying to hold it all together.\nIt’s okay to feel messy. Healing is not linear. Rest doesn’t mean failure. Try a 10-minute walk in nature—even near trees or plants. It’s been proven to lower cortisol levels and reset mental fatigue. Let the earth remind you: you’re already growing. You deserve quiet moments that help you remember who you are.",
  "You’re not behind. You’re not too late.\nThe rhythm of your life is your own, and comparison is a thief of joy. Today, pick one small thing you’ve been putting off—just one. Whether it’s a glass of water, a phone call, or organizing a corner of your room. Momentum begins with tiny wins. You deserve to feel proud of even your smallest steps.",
  "How’s your body doing today, honestly?\nHave you asked it lately? Gently stretch your fingers, wiggle your toes, unclench your jaw. Notice where you’re holding tension. Tiny moments of awareness prevent bigger breakdowns later. And if your eyes are tired, remember the 20-20-20 rule again—it really helps. You deserve care that meets you where you are, not just when you’re at your best.",
  "You are allowed to slow down.\nThere is no race. There is only today, and today you can breathe at your own pace. Take a moment to stretch your arms wide, take a deep breath, and let your body soften. Your muscles are working hard, and they deserve a gentle pause. And while you’re at it, make sure you’ve had a nutritious snack today—something that feeds your body, like fruit or a handful of nuts. You deserve time to rest and recharge.",
  "Your heart deserves rest, too.\nYou’re constantly giving, doing, and loving, but it’s okay to ask for a break. Listen to your body when it asks for rest. Take a deep breath, place a hand over your chest, and remind yourself that it’s safe to slow down. If you’ve been staring at a screen for hours, it’s time for a break. Follow the 20-20-20 rule—every 20 minutes, look at something 20 feet away for 20 seconds. It helps reduce strain. You deserve peace, and your body is asking for it today.",
  "How often do you check in with your own needs?\nWe often check in on others, but you deserve the same care. When was the last time you did something just for you? If you can, take a short walk, listen to music, or even sit in silence for a few minutes. Let yourself recharge. Movement boosts your mood and your energy, and it reminds you that you’re worthy of joy, even in small moments. You deserve space to breathe.",
  "Don’t forget to nurture your mind today.\nJust as you care for your body, take a moment to care for your thoughts. If stress is building, try meditating for five minutes. There’s no need to be perfect—simply let your breath guide you into calm. And remember to stay hydrated. Water is essential for focus and mental clarity. You deserve peace of mind and the stillness that supports it.",
  "How are you doing beneath the surface?\nThere’s so much going on that others don’t always see, but your feelings and energy are important. Start by doing something simple for yourself—like preparing a warm meal or stretching your body slowly. Nourishment feeds your soul and your body. And please, don’t forget to drink water today. Dehydration can cloud your thoughts and drain your energy. You deserve gentle care in every corner of your life.",
  "You deserve a moment of peace today.\nNo matter how busy life gets, please remember to carve out space for yourself. Whether it’s a quiet cup of tea or a walk in the fresh air, make room for calm. And while you’re at it, take a moment to stretch your body. Movement clears the mind and helps your energy flow. You deserve to feel at ease, no matter how chaotic the world around you may be.",
  "The work you do is important—but so are you.\nToday, take a pause to check in with your own well-being. It’s okay to step back for a moment. If you’ve been feeling tense, try this: close your eyes and do some gentle neck stretches. Release the tension in your shoulders. You also deserve time to rest, nourish, and recharge—your body is your partner in this journey. You deserve moments of quiet and self-love.",
  "You are already enough, exactly as you are.\nEven if you’ve been running on empty or feeling overwhelmed, you are enough. Take 5 minutes to breathe deeply and relax. Sit with your feet flat on the floor, hands on your heart, and just feel your breath move. And when was the last time you ate something full of color? A vibrant, nutrient-rich meal can fuel your body and your soul. You deserve to feel nourished, loved, and whole.",
  "You’re not just surviving, you’re living.\nIn the hustle of life, remember that each breath is a chance to reset. Try to move your body today in some way—even a few minutes of stretching or dancing can do wonders. And while you’re at it, don’t forget about hydration. Water keeps everything working smoothly, from your mind to your muscles. You deserve a life filled with energy and ease.",
  "You are worthy of joy, no matter what.\nEven on tough days, there is space for joy. Start small—find a moment to laugh, to breathe, or to simply enjoy being. If your mind feels cluttered, try a simple grounding exercise: focus on your senses, one at a time. Feel the ground beneath you. Notice the air on your skin. And don’t forget to eat something nourishing. Your body deserves the best care, every day. You deserve happiness, in the biggest and smallest ways."
];

function shuffleQuote() {
  const quoteElement = document.getElementById('quote');
  const randomIndex = Math.floor(Math.random() * quotes.length);
  quoteElement.textContent = quotes[randomIndex];
}

// Show a quote on initial page load
window.onload = shuffleQuote;